project_id = "obsidian-telegram"

[api]
enabled = true
port = 54321

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[functions.telegram-webhook]
verify_jwt = false

[functions.setup-bot]
verify_jwt = true
